LapTop/LapTop/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace LapTop.Controllers
{
    public class SanPhamController : Controller
    {
       
      
        
        public ActionResult ChiTiet()
        {
           
            return View();
        }
    }
}

LapTop/LapTop/Controllers/TrangChuController.cs
using LapTop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using PagedList;
using PagedList.Mvc;

namespace LapTop.Controllers
{
    public class TrangChuController : Controller
    {
        WEBEntities1 db = new WEBEntities1();

        public ActionResult Index(int? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var sp = db.SanPhams.ToList();
            var model = sp.OrderBy(x => x.ma).ToPagedList(pageNum, pageSize);

            return View(model);
        }
        // GET: TrangChu
        public ActionResult DanhMuc(int id, int? page)
        {
            var sanpham = db.SanPhams.Where(d => d.maDanhMuc == id).ToList();
            
            int pageSize = 2;
            int pageNum = (page ?? 1);
            var model = sanpham.OrderBy(x => x.ma).ToPagedList(pageNum, pageSize);

            return View(model);

        }
        [HttpGet]
        public ActionResult DangKi()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKi(FormCollection collection, Account acc)
        {
            string mail = collection["txtEmail"].ToString();
            string mk = collection["txtPassWord"].ToString();
            string ht = collection["txtFullName"].ToString();
            string dc = collection["txtDiaChi"].ToString();
            string sdt = collection["txtPhone"].ToString();
            bool gt = true;
            acc.mail = mail;
            acc.mk = mk;
            acc.hoten = ht;
            acc.diachi = dc;
            acc.sdt = sdt;
           
            db.Accounts.Add(acc);
            db.SaveChanges();
            //LỖi
            
            return RedirectToAction("Index");
        }
        
        public ActionResult ChiTiet()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ChiTiet(string masp)
        {
            ViewBag.masp = masp;
            return View();
        }
        [HttpGet]
        public ActionResult Timkiem(string q, int? page)
        {
            int pageSize = 4;
            int pageNum = (page ?? 1);
            var sp = db.SanPhams.Where(x => x.ten.Contains(q)).ToList();
            var model = sp.OrderBy(x => x.ma).ToPagedList(pageNum, pageSize);
            
            return View(model);
        }
    }
}

LapTop/LapTop/Views/Shared/Layout.cshtml
@using LapTop.Models;
@{
    WEBEntities1 db = new WEBEntities1();
    var DanhMuc = db.DanhMucs.ToList();
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <title>SHOP ONLINE</title>
    <link href="~/Style/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css.css" rel="stylesheet" />
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    @*start hinh gio hang*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v3.2"></script>

    <nav class="navbar navbar-expand-lg nav-bg">
        <a href="/TrangChu/Index" class="nav-link"><i class="fas fa-house-damage fa-lg"></i></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @foreach (var item in DanhMuc)
                {
                    <li class="nav-item">
                        <a href="/danh-muc/@item.ma" class="nav-link" , style="font-weight:bold">@item.ten</a>

                    </li>
                }


            </ul>
            <!---NÚT ĐĂNG NHẬP ĐĂNG KÍ-------------------------------------------->
            @Html.Action("GioHangPartial", "Giohang")
            @if (Session["TaiKhoan"] == null && Session["TenTaiKhoan"]==null)
            {
                <a href="/User/Dangnhap" class="btn btn-primary text-white mr-sm-2" data-toggle="modal" data-target="#exampleModal">Đăng Nhập</a>
                <a href="/User/DangKy" class="btn btn-primary text-white mr-sm-2">Đăng Ký</a>
            }
            else
            {
                 <a href="/User/DangXuat" class="btn btn-primary text-white mr-sm-2" id="logout">Đăng Xuất</a>
            }
            @using (Html.BeginForm("Timkiem", "TrangChu", FormMethod.Get, new { @class = "form-inline my-2 my-lg-0" }))
            {
                @Html.TextBox("q", "", new { @class = "form-control mr-sm-2", @type = "search", @placeholder = "Tim San Pham" })
                <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            }
        </div>
    </nav>
    <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">

                    <img src="../images/pan1jpg.jpg" class="d-block" height="300px" width="100%">
                </div>
                <div class="carousel-item">

                    <img src="../images/pan2.jpg" class="d-block" alt="..." height="300px" width="100%">
                </div>
                <div class="carousel-item">

                    <img src="../images/pan3.jpg" class="d-block" alt="..." height="300px" width="100%">
                </div>

            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
        <div>
            @RenderBody()
        </div>

        <!--Form dang nhap-->
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">ĐĂNG NHẬP</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @using (Html.BeginForm("Dangnhap", "User", FormMethod.Post))
                        {
                            <div class="modal-body">

                                <div class="form-group">
                                    <label for="exampleInputEmail1">Email address @ViewData["Loi1"]</label>
                                    @Html.TextBox("tendangnhap", "", new { @class = "form-control", @id = "mail", @placeholder = "Enter email" })

                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Password @ViewData["Loi2"]</label>
                                    @Html.Password("mk", "", new { @class = "form-control", @id = "mk", @placeholder = "Enter email" })

                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Đăng nhập</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
    </div>
    <div class="container">
        <div class="fb-page" data-href="https://www.facebook.com/facebook" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
            <blockquote cite="https://www.facebook.com/facebook" class="fb-xfbml-parse-ignore">
                <a href="https://www.facebook.com/facebook">Facebook</a>
            </blockquote>
        </div>
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.120335130727!2d106.71240001433067!3d10.802094592304126!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528a459cb43ab%3A0x6c3d29d370b52a7e!2zVHLGsOG7nW5nIMSQ4bqhaSBo4buNYyBIdXRlY2g!5e0!3m2!1svi!2s!4v1552909764574" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
        <a href="https://www.baokim.vn/payment/product/version11?business=quenlatot%40gmail.com&id=&order_description=H%C3%A0ng+ch%C3%ADnh+h%E1%BA%A3ng+b%E1%BA%A3o+h%C3%A0nh+t%E1%BB%91t&product_name=Chu%E1%BB%99t+Asus&product_price=2000000&product_quantity=1&total_amount=2000000&url_cancel=&url_detail=&url_success="><img src="~/image_product/baokim.jpg"  alt="Thanh toán an toàn với Bảo Kim !" border="1" title="Thanh toán trực tuyến an toàn dùng tài khoản Ngân hàng (VietcomBank, TechcomBank, Ðông Á, VietinBank, Quân Ð?i, VIB, SHB,... và thẻ Quốc tế (Visa, Master Card...) qua Cổng thanh toán trực tuyến BaoKim.vn"></a>
       
    </div>
    <div class="footer bg-dark text-white">
        <div class="container">
            <h1 class="display-4">LIÊN HỆ VỚI SHOP</h1>
            <p class="lead">
                <ul class="list-group">
                    <h5>Thứ 2 đến CN: 9h - 18h (Hotline), 7h - 22h (chat trực tuyến)</h5>
                    <h5>Trung tâm hỗ trợ</h5>
                    <h5>Hướng dẫn đặt hàng</h5>
                    <h5>Giao hàng và nhận hàng</h5>
                    <h5>Hướng dẫn đổi trả hàng </h5>
                    <h5>Địa Chỉ: Số 62 Đình Phong Phú, phường Tăng Nhơn Phú B, Quận 9, Thành Phố Hồ Chí Minh </h5>
                </ul>
            </p>
        </div>
    </div>
    <!------------------------------------------------------->
    <!------------------------------------------------------->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    
</body>
</html>

LapTop/LapTop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @{ 
     
    }
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

LapTop/LapTop/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <!-- Custom CSS -->
    <link href="~/Content/shop-homepage.css" rel="stylesheet" />
    <script>tinymce.init({ selector: 'textarea' });</script>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/tinymce/js/tinymce/tinymce.min.js"></script>
    <script>tinymce.init({ selector: 'textarea' });</script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">SHOP ONLINE</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("TRANG CHỦ", "Index", "Admin")
                    </li>
                    @*<li>
                        @Html.ActionLink("QUẢN LÝ CHỦ ĐỀ", "Sanpham", "Admin")
                    </li>*@
                    <li>
                        @Html.ActionLink("QUẢN LÝ NHÀ CUNG CẤP", "DanhMuc", "Admin")
                    </li>
                    <li>
                        @Html.ActionLink("QUẢN LÝ SẢN PHẨM", "SanPham", "Admin")

                    </li>
                    <li>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div>
            @RenderBody()
        </div>

    </div>
    </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <script src="~/Scripts/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>


</body>
</html>

LapTop/LapTop/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>